version: 2.1

jobs:
  lint_and_test:
    docker:
      - image: python:3.11

    steps: # a collection of executable commands making up the 'build' job
      - checkout # pulls source code to the working directory

      - run: # Activate virtual environment with pip and install dependencies
          name: Install dependencies
          command: |
            python3 -m venv env
            source env/bin/activate
            python3 -m pip install -r requirements.txt
            python3 manage.py collectstatic

      - run:
          name: Run tests and lint
          command: |
            source env/bin/activate
            flake8
            pytest
            pytest --cov
            coverage report -m --fail-under 80

      - store_artifacts:
          path: .coverage
          destination: coverage
  

  build:
    docker:
      image: python:3.11
    
    steps:
      - checkout
      - setup_remote_docker
      
      - run:
          name: Build Docker image
          command: |
            TAG=$CIRCLE_SHA1
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker build -t $DOCKER_IMAGE:$CIRCLE_SHA1 .
            docker build -t $DOCKER_IMAGE:latest .
            docker push $DOCKER_IMAGE:$CIRCLE_SHA1
            docker push $DOCKER_IMAGE:latest

  deploy:
    machine: true

    steps:
      - checkout

      - run:
          name: Push to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a  oc-lettings-13 web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a oc-lettings-13 web
      

workflows:
  run_tests:
    jobs:
      - lint_and_test
      - build:
          requires:
            - lint_and_test
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      

