version: 2.1

jobs:
  build_and_test:
    docker:
      - image: python:3.11

    steps: # a collection of executable commands making up the 'build' job
      - checkout # pulls source code to the working directory

      - run: # Activate virtual environment with pip and install dependencies
          name: Install dependencies
          command: |
            python3 -m venv env
            source env/bin/activate
            python3 -m pip install -r requirements.txt
            python3 manage.py collectstatic

      - run:
          name: Run tests and lint

            source env/bin/activate
            flake8
            pytest
            pytest --cov
            coverage report -m --fail-under 80

      - store_artifacts:
          path: .coverage
          destination: coverage
  

  build_and_deploy:
    docker:
      - image: python:3.11
    
    steps:
      - checkout

      - run:
          name: Build Docker image
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker build -t hgxv99/13_lettings .
            docker push hgxv99/13_lettings

      - run:
          name: Push to Heroku
          command: |
            apt-get install -y sudo
            ls -al /bin/sh && sudo rm /bin/sh && sudo ln -s /bin/bash /bin/sh && ls -al /bin/sh
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a  oc-lettings-13 web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a oc-lettings-13 web
      

workflows:
  run_tests:
    jobs:
      - build_and_test

